<?
$cmarc3_data = explode(":", $this->detail{"value"});
echo "cmarc3 $this->UUID<br>\n";

$Cmarc3 = new Application_Model_DbTable_Cmarc3structure();
foreach ($cmarc3_data as $field){
	list($tagfield, $tagsubfield, $value) = explode(",", $field);
	$desc = $Cmarc3->getDesc($tagfield,$tagsubfield);
	echo "$tagfield $tagsubfield $desc $value<br>\n";
    }
?>
<hr>

<a href="convert">convert</a><br>

<a href="/cmarc3/edit/UUID/<?=$this->UUID?>">edit</a><br>

<a href="/cmarc3/delete/UUID/<?=$this->UUID?>">delete</a><br>
