<div class="ipage">
<?php  if ($this->pageCount): ?>
<!-- First page link -->
<?php  if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->first)); ?>">
第一頁
</a> |
<?php  else: ?>
<span class="disabled">第一頁</span> |
<?php  endif; ?>

<!-- Previous page link -->
<?php  if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
&lt; 前一頁
</a> |
<?php  else: ?>
<span class="disabled">&lt; 前一頁</span> |
<?php  endif; ?>

<!-- Numbered page links -->
<?php  foreach ($this->pagesInRange as $page): ?>
<?php  if ($page != $this->current): ?>
<a href="<?php echo  $this->url(array('page' => $page)); ?>">
<?php echo  $page; ?>
</a> |
<?php  else: ?>
<?php echo  $page; ?> |
<?php  endif; ?>
<?php  endforeach; ?>

<!-- Next page link -->
<?php  if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->next)); ?>">
下一頁 &gt;
</a> |
<?php  else: ?>
<span class="disabled">下一頁 &gt;</span> |
<?php  endif; ?>

<!-- Last page link -->
<?php  if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->last)); ?>">
最後頁
</a>
<?php  else: ?>
<span class="disabled">最後頁</span>
<?php  endif; ?>

</div>
<?php  endif; ?>
