<?
$dublincore_data = explode(":", $this->detail{"value"});
echo "dublincore $this->UUID<br>\n";

foreach ($dublincore_data as $field){
	list($tagfield, $tagsubfield, $value) = explode(",", $field);
	echo "$tagfield $tagsubfield $value<br>\n";
    }
?>
<hr>

<a href="convert">convert</a><br>

<a href="/dublincore/edit/UUID/<?=$this->UUID?>">edit</a><br>

<a href="/dublincore/delete/UUID/<?=$this->UUID?>">delete</a><br>
