<?
$marc21_data = explode(":", $this->detail{"value"});
echo "marc21 $this->UUID<br>\n";

foreach ($marc21_data as $field){
	list($tagfield, $tagsubfield, $value) = explode(",", $field);
	echo "$tagfield $tagsubfield $value<br>\n";
    }
?>
<hr>

<a href="convert">convert</a><br>

<a href="/marc21/edit/UUID/<?=$this->UUID?>">edit</a><br>

<a href="/marc21/delete/UUID/<?=$this->UUID?>">delete</a><br>
